"""Initial migration with role_id

Revision ID: 5bc897babdc1
Revises: 
Create Date: 2025-11-16 21:06:32.108871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc897babdc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('vendor')
    # op.drop_table('customer')
    op.drop_table('purchase_order')
    op.drop_table('employee')
    op.drop_table('timebook')
    op.drop_table('job')
    op.drop_table('contact')
    op.drop_table('user')
    op.drop_table('vessel')
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vessel_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vessel_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('imo_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('mmsi_number', sa.VARCHAR(length=9), nullable=True),
    sa.Column('call_sign', sa.VARCHAR(length=10), nullable=True),
    sa.Column('flag_state', sa.VARCHAR(length=100), nullable=True),
    sa.Column('home_port', sa.VARCHAR(length=100), nullable=True),
    sa.Column('owner_operator', sa.VARCHAR(length=100), nullable=True),
    sa.Column('build_year', sa.INTEGER(), nullable=True),
    sa.Column('gross_tonnage_gt', sa.FLOAT(), nullable=True),
    sa.Column('length_overall_loa', sa.FLOAT(), nullable=True),
    sa.Column('beam', sa.FLOAT(), nullable=True),
    sa.Column('draft', sa.FLOAT(), nullable=True),
    sa.Column('vessel_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('propulsion_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('speed', sa.FLOAT(), nullable=True),
    sa.Column('uscg_documentation', sa.VARCHAR(length=50), nullable=True),
    sa.Column('classification_society', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ism_certification', sa.VARCHAR(length=50), nullable=True),
    sa.Column('solas_compliance', sa.VARCHAR(length=50), nullable=True),
    sa.Column('marpol_certification', sa.VARCHAR(length=50), nullable=True),
    sa.Column('load_line_certificate', sa.VARCHAR(length=50), nullable=True),
    sa.Column('radio_license', sa.VARCHAR(length=50), nullable=True),
    sa.Column('radar_system', sa.VARCHAR(length=100), nullable=True),
    sa.Column('chartplotter_ecdis', sa.VARCHAR(length=100), nullable=True),
    sa.Column('autopilot', sa.VARCHAR(length=100), nullable=True),
    sa.Column('communication_systems', sa.VARCHAR(length=200), nullable=True),
    sa.Column('security_systems', sa.VARCHAR(length=200), nullable=True),
    sa.Column('electrical_systems', sa.VARCHAR(length=200), nullable=True),
    sa.Column('route_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('jones_act_compliance', sa.VARCHAR(length=50), nullable=True),
    sa.Column('passenger_cargo_capacity', sa.INTEGER(), nullable=True),
    sa.Column('inspection_history', sa.TEXT(), nullable=True),
    sa.Column('service_area', sa.VARCHAR(length=200), nullable=True),
    sa.Column('maintenance_log', sa.TEXT(), nullable=True),
    sa.Column('upgrade_history', sa.TEXT(), nullable=True),
    sa.Column('incident_reports', sa.TEXT(), nullable=True),
    sa.Column('expiration_alerts', sa.TEXT(), nullable=True),
    sa.Column('assignment_eligibility', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('permissions', sa.TEXT(), nullable=True),
    sa.Column('employee_full_name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timebook',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('time_date', sa.DATE(), nullable=True),
    sa.Column('start_time', sa.VARCHAR(length=5), nullable=True),
    sa.Column('stop_time', sa.VARCHAR(length=5), nullable=True),
    sa.Column('job', sa.VARCHAR(length=100), nullable=True),
    sa.Column('job_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('mileage', sa.INTEGER(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('pay_rate_rt', sa.FLOAT(), nullable=True),
    sa.Column('pay_rate_ot', sa.FLOAT(), nullable=True),
    sa.Column('paid', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('contact_info', sa.VARCHAR(length=200), nullable=True),
    sa.Column('address', sa.VARCHAR(length=300), nullable=True),
    sa.Column('hire_date', sa.DATE(), nullable=True),
    sa.Column('role_position', sa.VARCHAR(length=100), nullable=True),
    sa.Column('payrate_rt', sa.FLOAT(), nullable=True),
    sa.Column('payrate_ot', sa.FLOAT(), nullable=True),
    sa.Column('stcw_certification', sa.VARCHAR(length=200), nullable=True),
    sa.Column('twic_card', sa.VARCHAR(length=200), nullable=True),
    sa.Column('merchant_mariner_credential_mmc', sa.VARCHAR(length=200), nullable=True),
    sa.Column('electro_technical_officer_eto_certification', sa.VARCHAR(length=200), nullable=True),
    sa.Column('osha_safety_certifications', sa.VARCHAR(length=200), nullable=True),
    sa.Column('first_aid_cpr_aed', sa.VARCHAR(length=200), nullable=True),
    sa.Column('huet_bosiet', sa.VARCHAR(length=200), nullable=True),
    sa.Column('gmdss_operator', sa.VARCHAR(length=200), nullable=True),
    sa.Column('vessel_tonnage_rating', sa.VARCHAR(length=100), nullable=True),
    sa.Column('domestic_international_endorsement', sa.VARCHAR(length=100), nullable=True),
    sa.Column('able_seafarer_deck_engine_ab_rating', sa.VARCHAR(length=200), nullable=True),
    sa.Column('radar_arpa_endorsement', sa.VARCHAR(length=200), nullable=True),
    sa.Column('ecdis_certification', sa.VARCHAR(length=200), nullable=True),
    sa.Column('power_tools_proficiency', sa.VARCHAR(length=200), nullable=True),
    sa.Column('multi_meter_usage', sa.VARCHAR(length=200), nullable=True),
    sa.Column('nvrip_camera_systems', sa.VARCHAR(length=200), nullable=True),
    sa.Column('marine_electronics_expertise', sa.VARCHAR(length=200), nullable=True),
    sa.Column('uhf_vhf_radio_handling', sa.VARCHAR(length=200), nullable=True),
    sa.Column('years_of_experience', sa.INTEGER(), nullable=True),
    sa.Column('training_completion_log', sa.TEXT(), nullable=True),
    sa.Column('performance_reviews', sa.TEXT(), nullable=True),
    sa.Column('upgrade_eligibility_flags', sa.VARCHAR(length=200), nullable=True),
    sa.Column('promotion_history', sa.TEXT(), nullable=True),
    sa.Column('expiration_alerts', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
